version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.4
      - test-3.5
      - test-3.6
jobs:
  test-3.4: &test-template
    working_directory: ~/visidata
    docker:
      - image: circleci/python:3.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/share
      - run: sudo chown -R circleci:circleci /usr/local/lib
      - run: sudo locale-gen en_CA.UTF-8 && sudo locale-gen en en_CA.UTF-8 && sudo dpkg-reconfigure locales
      - run: update-locale LANG=en_US.UTF-8
      - run:
          name: dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          command: |
            dev/test.sh
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
