version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.4
        steps:
            - checkout
            - run:
                name: dependencies
                command: pip3 install -r requirements.txt
            - run: dev/test.sh

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
