version: 2
jobs:
  build:
    working_directory: ~/visidata
    docker:
      - image: circleci/python:3.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/share
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.4/site-packages
      - run:
          name: dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          command: |
            dev/test.sh
